### ISSUE TITLE
Plans for Webpack 5?

### ISSUE THREAD

**Issue by lassemt** [iampava/imagemin-webp-webpack-plugin#38]
Firstly, great work with this package!

I know it is highlighted in the readme that this package is supporting Webpack 4 and down. Is it on the roadmap to support Webpack 5? Webpack 5 was released last week.

**Comment by iampava** [comment]
Hey!

Yes, will definitely upgrade it to Webpack 5. Haven't scheduled any work for this yet but will definitely happen in the few weeks, as people begin transitioning to Webpack 5.

**Comment by Pr3s4ri0** [comment]
Hay, Any progress on that ?
Currently after migration to Webpack 5 it produces DeprecationWarning:
 
> webpack --mode production

(node:82537) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
```
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
imagemin-webp-webpack-plugin: 2.7 MB saved
```
running 
`$ node --trace-deprecation ./node_modules/.bin/webpack`
with installed
```
├── imagemin-webp-webpack-plugin@3.3.3
└── webpack@5.16.0
```
shows 
```
(node:85996) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at ./node_modules/imagemin-webp-webpack-plugin/plugin.js:63:68
    at async Promise.all (index 14)
```

**Comment by iampava** [comment]
Done!

**Comment by lid2000** [comment]
I'm still getting this warning, running Webpack 5.51.1 and imagemin-web-webpack-plugin 3.3.6. I've tried shifting the plugin order around, but it makes no difference whether this is first or last in the list - the warning still happens.

```
95% emitting emit ImageminWebpWebpackPlugin(node:16748) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at Compilation.emitAsset (./node_modules/webpack/lib/Compilation.js:3525:21)
    at emitAsset (./node_modules/imagemin-webp-webpack-plugin/plugin.js:133:21)
    at ./node_modules/imagemin-webp-webpack-plugin/plugin.js:68:37
    at async Promise.all (index 0)
imagemin-webp-webpack-plugin: 0.7 MB saved
```

**Comment by iampava** [comment]
Is the test project inside `/test-project-webpack5` running ok or is it also throwing the above warning?

**Comment by dima-po** [comment]
In version 3.3.6 still getting this warning

`95% emitting emit ImageminWebpWebpackPlugin(node:38292) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.`
